name: Deployment pipeline

env:
  noSkip: ${{ !contains(join(github.event.commits.*.message, ', '), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install browsers
        run: npx playwright install
      - name: Install browser dependencies
        run: sudo npx playwright install-deps
      - name: Check style
        run: npm run eslint
      - name: build
        id: build
        run: build failing
        # run: npm run build
      - name: test
        run: npm test
      - name: test end-2-end
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && fromJson(env.noSkip) }}
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true
      - name: Bump version and push tag
        if: ${{ fromJson(env.noSkip) }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: New version of Pokedex deployed!
        if: ${{ success() && github.event_name == 'push' && fromJson(env.noSkip) }}
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: New version of Pokedex deployed!
          message: "to\nhttps://full-stack-open-pokedex-rqf4.onrender.com by ${{ github.event.pusher.name }}"
          colour: '#45f542'
      - name: Build failed!
        if: ${{ failure() && steps.build.conclusion == 'failure' }}
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Build failed
          message: 'commit ${{ github.event.head_commit.url }} by ${{ github.event.pusher.name }} broke the build'
          colour: '#ff0303'
